name: dart_tg_bot_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  dotenv: ^4.2.0
  sqlite3: ^2.4.2
  teledart: ^0.6.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
